In [66]:
import pandas as pd

In [67]:
df = pd.read_csv("../data/raw/pl_2022_23.csv", sep=";", encoding="latin-1")
df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
0,1,Brenden Aaronson,USA,MFFW,Leeds United,Premier League,22,2000,20,19,...,0.17,2.54,0.51,0.0,0.0,0.00,4.86,0.34,1.19,22.2
1,2,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,1987,22,22,...,0.05,0.18,1.59,0.0,0.0,0.00,6.64,2.18,1.23,64.0
2,3,Himad Abdelli,FRA,MFFW,Angers,Ligue 1,23,1999,14,8,...,0.00,1.05,1.40,0.0,0.0,0.00,8.14,0.93,1.05,47.1
3,4,Salis Abdul Samed,GHA,MF,Lens,Ligue 1,22,2000,20,20,...,0.00,0.35,0.80,0.0,0.0,0.05,6.60,0.50,0.50,50.0
4,5,Laurent Abergel,FRA,MF,Lorient,Ligue 1,30,1993,15,15,...,0.00,0.23,2.02,0.0,0.0,0.00,6.51,0.31,0.39,44.4

In [68]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2689 entries, 0 to 2688
Columns: 124 entries, Rk to AerWon%
dtypes: float64(112), int64(7), object(5)
memory usage: 2.5+ MB

In [69]:
df = df[df["Comp"] == "Premier League"]
df.shape

(540, 124)

In [70]:
df = df[df["Pos"] != "GK"]
df.shape

(511, 124)

In [71]:
df["Pos"].value_counts()

Pos
DF      170
MF      115
FW       97
MFFW     48
FWMF     46
DFMF     14
FWDF      9
MFDF      9
DFFW      3
Name: count, dtype: int64

In [72]:
df["Player"].value_counts().head(20)

Player
Wesley Fofana             2
Leandro Trossard          2
Danny Ings                2
Craig Dawson              2
Daniel James              2
Jorginho                  2
Leander Dendoncker        2
Anthony Gordon            2
Morgan Gibbs-White        2
Albert Sambi Lokonga      2
Jonjo Shelvey             2
Cédric Soares             2
Jack Stephens             2
Chris Wood                2
Jan Bednarek              2
Carlos Alcaraz            1
Trent Alexander-Arnold    1
Dele Alli                 1
Miguel Almirón            1
James Tarkowski           1
Name: count, dtype: int64

In [73]:
df = df.groupby("Player", as_index=False).sum(numeric_only=True)
df.shape

(496, 120)

In [74]:
import pandas as pd

df = pd.read_csv("../data/raw/pl_2022_23.csv", sep=";", encoding="latin-1")

In [75]:
df = df[df["Comp"] == "Premier League"]

In [76]:
df = df[df["Pos"] != "GK"]

In [77]:
df.shape

(511, 124)

In [78]:
df = df.groupby("Player", as_index=False).agg({
    "Squad": "first",
    "Pos": "first",
    "Min": "sum",
    "90s": "sum"
}).merge(
    df.groupby("Player").sum(numeric_only=True),
    on="Player"
)

In [79]:
df.shape

(496, 124)

In [80]:
df["Min"] = df["Min_y"]
df["90s"] = df["90s_y"]

In [81]:
df = df.drop(columns=["Min_x","90s_x","Min_y","90s_y"])

In [82]:
df[["Min","90s"]].head()

    Min   90s
0  1533  17.0
1   739   8.2
2   609   6.8
3   318   3.5
4  1027  11.4

In [83]:
scs_columns = [
    "Player","Squad","Pos","Min","90s",

    # Defensive impact
    "Tkl","Int","Blocks","Clr",

    # Pressing
    "TklDef3rd","TklMid3rd","TklAtt3rd","Recov",

    # Progression
    "PasProg","CarProg","CarPrgDist","Pas3rd",

    # Chance creation
    "PasAss","SCA","PPA","TB",

    # Possession retention
    "PasTotCmp%","CarMis","CarDis",

    # Activity
    "Touches","Carries","Rec"
]

df = df[scs_columns]

In [84]:
df.head()

,Player,Squad,Pos,Min,90s,Tkl,Int,Blocks,Clr,TklDef3rd,...,PasAss,SCA,PPA,TB,PasTotCmp%,CarMis,CarDis,Touches,Carries,Rec
0,Aaron Cresswell,West Ham,DF,1533,17.0,0.82,1.18,1.00,2.35,0.47,...,1.76,3.12,1.41,0.06,79.6,0.24,0.35,70.8,33.5,43.3
1,Aaron Hickey,Brentford,DF,739,8.2,2.32,1.34,1.22,1.34,1.34,...,0.12,0.85,0.61,0.00,81.0,0.85,0.49,49.3,30.2,30.7
2,Aaron Wan-Bissaka,Manchester Utd,DF,609,6.8,2.65,1.91,1.03,2.65,1.91,...,0.88,1.76,0.44,0.00,82.1,1.18,0.74,59.4,29.7,32.9
3,Abdoulaye Doucouré,Everton,MF,318,3.5,2.00,0.57,1.14,0.86,0.57,...,0.29,1.43,0.00,0.00,78.5,0.86,0.57,49.7,27.7,32.3
4,Adam Armstrong,Southampton,FW,1027,11.4,0.88,0.26,1.14,0.44,0.26,...,0.88,1.58,0.79,0.00,73.4,1.40,1.32,32.2,18.2,19.4

In [85]:
df.shape

(496, 27)

In [86]:
per90_columns = [
    "Tkl","Int","Blocks","Clr",
    "TklDef3rd","TklMid3rd","TklAtt3rd","Recov",
    "PasProg","CarProg","CarPrgDist","Pas3rd",
    "PasAss","SCA","PPA","TB",
    "Touches","Carries","Rec"
]

for col in per90_columns:
    df[col + "_p90"] = df[col] / df["90s"]

In [87]:
df.head()

,Player,Squad,Pos,Min,90s,Tkl,Int,Blocks,Clr,TklDef3rd,...,CarProg_p90,CarPrgDist_p90,Pas3rd_p90,PasAss_p90,SCA_p90,PPA_p90,TB_p90,Touches_p90,Carries_p90,Rec_p90
0,Aaron Cresswell,West Ham,DF,1533,17.0,0.82,1.18,1.00,2.35,0.47,...,0.093529,4.376471,0.259412,0.103529,0.183529,0.082941,0.003529,4.164706,1.970588,2.547059
1,Aaron Hickey,Brentford,DF,739,8.2,2.32,1.34,1.22,1.34,1.34,...,0.326829,12.036585,0.371951,0.014634,0.103659,0.074390,0.000000,6.012195,3.682927,3.743902
2,Aaron Wan-Bissaka,Manchester Utd,DF,609,6.8,2.65,1.91,1.03,2.65,1.91,...,0.345588,12.176471,0.476471,0.129412,0.258824,0.064706,0.000000,8.735294,4.367647,4.838235
3,Abdoulaye Doucouré,Everton,MF,318,3.5,2.00,0.57,1.14,0.86,0.57,...,0.162857,17.885714,0.734286,0.082857,0.408571,0.000000,0.000000,14.200000,7.914286,9.228571
4,Adam Armstrong,Southampton,FW,1027,11.4,0.88,0.26,1.14,0.44,0.26,...,0.253509,6.350877,0.084211,0.077193,0.138596,0.069298,0.000000,2.824561,1.596491,1.701754

In [88]:
df.shape

(496, 46)

In [89]:
df.columns

Index(['Player', 'Squad', 'Pos', 'Min', '90s', 'Tkl', 'Int', 'Blocks', 'Clr',
       'TklDef3rd', 'TklMid3rd', 'TklAtt3rd', 'Recov', 'PasProg', 'CarProg',
       'CarPrgDist', 'Pas3rd', 'PasAss', 'SCA', 'PPA', 'TB', 'PasTotCmp%',
       'CarMis', 'CarDis', 'Touches', 'Carries', 'Rec', 'Tkl_p90', 'Int_p90',
       'Blocks_p90', 'Clr_p90', 'TklDef3rd_p90', 'TklMid3rd_p90',
       'TklAtt3rd_p90', 'Recov_p90', 'PasProg_p90', 'CarProg_p90',
       'CarPrgDist_p90', 'Pas3rd_p90', 'PasAss_p90', 'SCA_p90', 'PPA_p90',
       'TB_p90', 'Touches_p90', 'Carries_p90', 'Rec_p90'],
      dtype='object')