In [1239]:
import pandas as pd

In [1240]:
df = pd.read_csv("../data/raw/epl_2022-23.csv", sep=";", encoding="latin-1")
df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
0,1,Brenden Aaronson,USA,MFFW,Leeds United,Premier League,22,2000,20,19,...,0.17,2.54,0.51,0.0,0.0,0.00,4.86,0.34,1.19,22.2
1,2,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,1987,22,22,...,0.05,0.18,1.59,0.0,0.0,0.00,6.64,2.18,1.23,64.0
2,3,Himad Abdelli,FRA,MFFW,Angers,Ligue 1,23,1999,14,8,...,0.00,1.05,1.40,0.0,0.0,0.00,8.14,0.93,1.05,47.1
3,4,Salis Abdul Samed,GHA,MF,Lens,Ligue 1,22,2000,20,20,...,0.00,0.35,0.80,0.0,0.0,0.05,6.60,0.50,0.50,50.0
4,5,Laurent Abergel,FRA,MF,Lorient,Ligue 1,30,1993,15,15,...,0.00,0.23,2.02,0.0,0.0,0.00,6.51,0.31,0.39,44.4

In [1241]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2689 entries, 0 to 2688
Columns: 124 entries, Rk to AerWon%
dtypes: float64(112), int64(7), object(5)
memory usage: 2.5+ MB

In [1242]:
df = df[df["Comp"] == "Premier League"]
df.shape

(540, 124)

In [1243]:
df = df[df["Pos"] != "GK"]
df.shape

(511, 124)

In [1244]:
df["Pos"].value_counts()

Pos
DF      170
MF      115
FW       97
MFFW     48
FWMF     46
DFMF     14
FWDF      9
MFDF      9
DFFW      3
Name: count, dtype: int64

In [1245]:
df["Player"].value_counts().head(20)

Player
Wesley Fofana             2
Leandro Trossard          2
Danny Ings                2
Craig Dawson              2
Daniel James              2
Jorginho                  2
Leander Dendoncker        2
Anthony Gordon            2
Morgan Gibbs-White        2
Albert Sambi Lokonga      2
Jonjo Shelvey             2
Cédric Soares             2
Jack Stephens             2
Chris Wood                2
Jan Bednarek              2
Carlos Alcaraz            1
Trent Alexander-Arnold    1
Dele Alli                 1
Miguel Almirón            1
James Tarkowski           1
Name: count, dtype: int64

In [1246]:
df = df.groupby("Player", as_index=False).sum(numeric_only=True)
df.shape

(496, 120)

In [1247]:
import pandas as pd

df = pd.read_csv("../data/raw/epl_2022-23.csv", sep=";", encoding="latin-1")

In [1248]:
df = df[df["Comp"] == "Premier League"]

In [1249]:
df = df[df["Pos"] != "GK"]

In [1250]:
df.shape

(511, 124)

In [1251]:
df = df.groupby("Player", as_index=False).agg({
    "Squad": "first",
    "Pos": "first",
    "Min": "sum",
    "90s": "sum"
}).merge(
    df.groupby("Player").sum(numeric_only=True),
    on="Player"
)

In [1252]:
df.shape

(496, 124)

In [1253]:
df["Min"] = df["Min_y"]
df["90s"] = df["90s_y"]

In [1254]:
df = df.drop(columns=["Min_x","90s_x","Min_y","90s_y"])

In [1255]:
df[["Min","90s"]].head()

    Min   90s
0  1533  17.0
1   739   8.2
2   609   6.8
3   318   3.5
4  1027  11.4

In [1256]:
scs_columns = [
    "Player","Squad","Pos","Min","90s",

    # Defensive impact
    "Tkl","Int","Blocks","Clr",

    # Pressing
    "TklDef3rd","TklMid3rd","TklAtt3rd","Recov",

    # Progression
    "PasProg","CarProg","CarPrgDist","Pas3rd",

    # Chance creation
    "PasAss","SCA","PPA","TB",

    # Possession retention
    "PasTotCmp%","CarMis","CarDis",

    # Activity
    "Touches","Carries","Rec"
]

df = df[scs_columns]

In [1257]:
df.head()

,Player,Squad,Pos,Min,90s,Tkl,Int,Blocks,Clr,TklDef3rd,...,PasAss,SCA,PPA,TB,PasTotCmp%,CarMis,CarDis,Touches,Carries,Rec
0,Aaron Cresswell,West Ham,DF,1533,17.0,0.82,1.18,1.00,2.35,0.47,...,1.76,3.12,1.41,0.06,79.6,0.24,0.35,70.8,33.5,43.3
1,Aaron Hickey,Brentford,DF,739,8.2,2.32,1.34,1.22,1.34,1.34,...,0.12,0.85,0.61,0.00,81.0,0.85,0.49,49.3,30.2,30.7
2,Aaron Wan-Bissaka,Manchester Utd,DF,609,6.8,2.65,1.91,1.03,2.65,1.91,...,0.88,1.76,0.44,0.00,82.1,1.18,0.74,59.4,29.7,32.9
3,Abdoulaye Doucouré,Everton,MF,318,3.5,2.00,0.57,1.14,0.86,0.57,...,0.29,1.43,0.00,0.00,78.5,0.86,0.57,49.7,27.7,32.3
4,Adam Armstrong,Southampton,FW,1027,11.4,0.88,0.26,1.14,0.44,0.26,...,0.88,1.58,0.79,0.00,73.4,1.40,1.32,32.2,18.2,19.4

In [1258]:
df.shape

(496, 27)

In [1259]:
per90_columns = [
    "Tkl","Int","Blocks","Clr",
    "TklDef3rd","TklMid3rd","TklAtt3rd","Recov",
    "PasProg","CarProg","CarPrgDist","Pas3rd",
    "PasAss","SCA","PPA","TB",
    "Touches","Carries","Rec"
]

for col in per90_columns:
    df[col + "_p90"] = df[col] / df["90s"]

In [1260]:
df.shape

(496, 46)

## Phase 4 – SCS Dimension Construction

In [1261]:
scs_dimensions = {
    "defensive_impact": ["Tkl_p90", "Int_p90", "Blocks_p90", "Clr_p90"],
    
    "pressing_ball_winning": ["TklDef3rd_p90", "TklMid3rd_p90", "TklAtt3rd_p90", "Recov_p90"],
    
    "ball_progression": ["PasProg_p90", "CarProg_p90", "CarPrgDist_p90", "Pas3rd_p90"],
    
    "chance_creation": ["PasAss_p90", "SCA_p90", "PPA_p90", "TB_p90"],
    
    "possession_retention": ["PasTotCmp%", "CarMis", "CarDis"],
    
    "off_ball_activity": ["Touches_p90", "Carries_p90", "Rec_p90"]
}

### Applying Minimum Minutes Threshold

In [1262]:
# Filter players who played at least 900 minutes
df = df[df["Min"] >= 900]

# Check new shape
df.shape

(211, 46)

### Standardizing Player Positions

In [1263]:
# Keep only the first listed position
df["Pos"] = df["Pos"].str[:2]

# Check the result
df["Pos"].value_counts()

Pos
DF    91
MF    71
FW    49
Name: count, dtype: int64

### Position-Based Percentile Normalization

In [1264]:
scs_metrics = [
    "Tkl_p90","Int_p90","Blocks_p90","Clr_p90",
    "TklDef3rd_p90","TklMid3rd_p90","TklAtt3rd_p90","Recov_p90",
    "PasProg_p90","CarProg_p90","CarPrgDist_p90","Pas3rd_p90",
    "PasAss_p90","SCA_p90","PPA_p90","TB_p90",
    "PasTotCmp%","CarMis","CarDis",
    "Touches_p90","Carries_p90","Rec_p90"
]

In [1265]:
for stat in scs_metrics:
    
    df[stat + "_pct"] = (
        df.groupby("Pos")[stat]
        .rank(pct=True) * 100
    )

[c for c in df.columns if "_pct" in c]

['Tkl_p90_pct',
 'Int_p90_pct',
 'Blocks_p90_pct',
 'Clr_p90_pct',
 'TklDef3rd_p90_pct',
 'TklMid3rd_p90_pct',
 'TklAtt3rd_p90_pct',
 'Recov_p90_pct',
 'PasProg_p90_pct',
 'CarProg_p90_pct',
 'CarPrgDist_p90_pct',
 'Pas3rd_p90_pct',
 'PasAss_p90_pct',
 'SCA_p90_pct',
 'PPA_p90_pct',
 'TB_p90_pct',
 'PasTotCmp%_pct',
 'CarMis_pct',
 'CarDis_pct',
 'Touches_p90_pct',
 'Carries_p90_pct',
 'Rec_p90_pct']

### Handling Negative Possession Metrics

In [1266]:
# Invert metrics where lower values are better
df["CarMis_pct"] = 100 - df["CarMis_pct"]
df["CarDis_pct"] = 100 - df["CarDis_pct"]

### Constructing SCS Performance Dimensions

In [1267]:
# Defensive Impact
df["defensive_impact"] = df[
    ["Tkl_p90_pct","Int_p90_pct","Blocks_p90_pct","Clr_p90_pct"]
].mean(axis=1)

# Pressing & Ball Winning
df["pressing_ball_winning"] = df[
    ["TklDef3rd_p90_pct","TklMid3rd_p90_pct","TklAtt3rd_p90_pct","Recov_p90_pct"]
].mean(axis=1)

# Ball Progression
df["ball_progression"] = df[
    ["PasProg_p90_pct","CarProg_p90_pct","CarPrgDist_p90_pct","Pas3rd_p90_pct"]
].mean(axis=1)

# Chance Creation
df["chance_creation"] = df[
    ["PasAss_p90_pct","SCA_p90_pct","PPA_p90_pct","TB_p90_pct"]
].mean(axis=1)

# Possession Retention
df["possession_retention"] = df[
    ["PasTotCmp%_pct","CarMis_pct","CarDis_pct"]
].mean(axis=1)

# Off Ball Activity
df["off_ball_activity"] = df[
    ["Touches_p90_pct","Carries_p90_pct","Rec_p90_pct"]
].mean(axis=1)

In [1268]:
df[
[
"defensive_impact",
"pressing_ball_winning",
"ball_progression",
"chance_creation",
"possession_retention",
"off_ball_activity"
]
].describe()

,defensive_impact,pressing_ball_winning,ball_progression,chance_creation,possession_retention,off_ball_activity
count,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000
mean,50.710900,50.710900,50.710900,50.710900,49.763033,50.710900
std,21.530762,21.924315,23.683039,24.252056,22.775557,28.455674
min,4.225352,2.806122,4.120879,2.992958,4.578755,1.098901
25%,34.517268,33.747126,30.367922,32.005495,31.227106,25.679719
50%,52.472527,51.236264,51.056338,48.591549,51.020408,52.380952
75%,65.752206,66.868519,68.661972,71.038732,66.901408,74.829932
max,97.448980,95.604396,98.469388,99.450549,92.957746,100.000000

### Shadow Contribution Score (SCS)

In [1269]:
scs_weights = {
    
    "DF": {
        "defensive_impact": 0.30,
        "pressing_ball_winning": 0.20,
        "ball_progression": 0.15,
        "chance_creation": 0.05,
        "possession_retention": 0.15,
        "off_ball_activity": 0.15
    },
    
    "MF": {
        "defensive_impact": 0.15,
        "pressing_ball_winning": 0.20,
        "ball_progression": 0.20,
        "chance_creation": 0.15,
        "possession_retention": 0.15,
        "off_ball_activity": 0.15
    },
    
    "FW": {
        "defensive_impact": 0.05,
        "pressing_ball_winning": 0.10,
        "ball_progression": 0.20,
        "chance_creation": 0.30,
        "possession_retention": 0.15,
        "off_ball_activity": 0.20
    }
}

In [1270]:
def calculate_scs(row):
    
    weights = scs_weights[row["Pos"]]
    
    score = (
        row["defensive_impact"] * weights["defensive_impact"] +
        row["pressing_ball_winning"] * weights["pressing_ball_winning"] +
        row["ball_progression"] * weights["ball_progression"] +
        row["chance_creation"] * weights["chance_creation"] +
        row["possession_retention"] * weights["possession_retention"] +
        row["off_ball_activity"] * weights["off_ball_activity"]
    )
    
    return score

df["SCS"] = df.apply(calculate_scs, axis=1)

### Player Leaderboard

In [1271]:
leaderboard = (
    df.sort_values("SCS", ascending=False)
    [["Player","Squad","Pos","SCS"]]
    .reset_index(drop=True)
)


leaderboard.insert(0, "Rank", leaderboard.index + 1)

leaderboard["SCS"] = leaderboard["SCS"].round(2)

# Added processed dataset

In [1272]:
df.to_csv("../data/processed/epl_2022-23_scs-ready.csv", index=False)

In [1273]:
raw_df = pd.read_csv("../data/raw/epl_2022-23.csv", sep=";", encoding="latin-1")

In [1274]:
goals_df = (
    raw_df.groupby("Player")["Goals"]
    .sum()
    .reset_index()
)

df = df.merge(goals_df, on="Player", how="left")

In [1275]:
df.sort_values("SCS", ascending=False)[["Player","Pos","SCS","Goals"]].head(20)

                 Player Pos        SCS  Goals
113    Leandro Trossard  FW  87.500000      8
105        Kaoru Mitoma  FW  84.723639      5
73        Jack Grealish  FW  83.460884      2
159          Phil Foden  FW  81.870748      7
187    Thiago Alcántara  MF  81.602113      0
95     Jordan Henderson  MF  81.091549      0
13               Antony  FW  80.059524      3
35      Clément Lenglet  DF  79.993132      0
169     Roberto Firmino  FW  79.481293      7
51        Dwight McNeil  FW  78.954082      2
155       Pablo Fornals  FW  78.741497      1
97             Jorginho  MF  78.353873      2
11       Anthony Gordon  MF  77.869718      3
29             Casemiro  MF  77.693662      2
145  Morgan Gibbs-White  FW  77.457483      2
39    César Azpilicueta  DF  77.314560      0
104   Kalidou Koulibaly  DF  76.875000      2
86            Joe Gomez  DF  76.325549      0
206             Willian  FW  76.062925      3
93         Jonny Castro  DF  76.002747      0